;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        kill-visual-line
        org-cycle
        org-end-of-line
        org-metaright
        org-self-insert-command
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        ))
